在继续提交一下

diff --git a/debian/godev-claude/Dockerfile b/debian/godev-claude/Dockerfile
--- a/debian/godev-claude/Dockerfile
+++ b/debian/godev-claude/Dockerfile
@@ -60,7 +60,20 @@ RUN /usr/local/go/bin/go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest 
     /usr/local/go/bin/go install honnef.co/go/tools/cmd/staticcheck@latest && \
     /usr/local/go/bin/go install golang.org/x/tools/gopls@latest
 
-RUN curl -fsSL https://claude.ai/install.sh | bash
+RUN node_version=24.15.0 && apt-get update && apt-get install -y xz-utils && \
+    case "$(arch)" in \
+        x86_64) arch_m="x64" ;; \
+        aarch64) arch_m="arm64" ;; \
+        *) echo >&2 "error: unsupported version: '$app_version'"; exit 1 ;; \
+    esac && \
+    wget https://nodejs.org/dist/v${node_version}/node-v${node_version}-linux-${arch_m}.tar.xz && \
+    tar xf node-v${node_version}-linux-${arch_m}.tar.xz -C /usr/local/ && \
+    rm -f node-v${node_version}-linux-${arch_m}.tar.xz && \
+    ln -sf /usr/local/node-v${node_version}-linux-${arch_m} /usr/local/node
+
+ENV PATH=$PATH:/usr/local/node/bin
+
+RUN npm install -g @anthropic-ai/claude-code@latest
 
 # 启动命令，主要就是先获取环境变量，然后让sshd 前台运行即可
 CMD ["bash", "-c", "bash /home/normaluser/get_env.sh;/usr/sbin/sshd -D -f /home/normaluser/ssh/sshd_config"]
