调整一下netcat

diff --git a/alpine/static-netcat/Dockerfile b/alpine/static-netcat/Dockerfile
--- a/alpine/static-netcat/Dockerfile
+++ b/alpine/static-netcat/Dockerfile
@@ -9,7 +9,15 @@ WORKDIR /packs
 RUN wget https://zenlayer.dl.sourceforge.net/project/netcat/netcat/${app_version}/netcat-${app_version}.tar.gz && \
     tar xf netcat-${app_version}.tar.gz  && \
     cd netcat-${app_version} && \
-    CFLAGS=-static ./configure --prefix=/packs/netcat && \
+    arch="$(arch)"; \
+    case "$arch" in \
+        'x86_64') CFLAGS=-static ./configure --prefix=/usr/local/netcat; \
+        ;; \
+        'aarch64') CFLAGS=-static ./configure --prefix=/usr/local/netcat --build=aarch64-unknown-linux-gnu; \
+        ;; \
+        *) echo >&2 "error: unsupported architecture: '$arch'"; exit 1; \
+        ;; \
+    esac; \
     make -j && make install 
 
 
